Implement multibase for C++
koinos/koinos-types pull request #171
Opened 2021-03-24 17:36 UTC by theoreticalbts

Closes #168.

2021-03-24 20:31 UTC, sgerbino requested changes
- We need more extensive coverage via testing of new code
- We shouldn't remove the bitcoin copyright
- The tests should be implemened as a Boost Test and run in CI

2021-06-17 18:45 UTC, theoreticalbts commented
The copyright wasn't removed, it was moved lower in the file.

For more clarity about what copyright applies to what code, I'm going to update the branch and put the code from Bitcoin in a separate header file from our code.

2021-06-18 19:04 UTC, theoreticalbts commented
Updated this PR:

- Addressed copyright issue
- Added tests
- Fixed several bugs uncovered by the tests

Also added a Monte Carlo test which you can run forever by:

```
    ../programs/test_multibase/multibase_mc.py | programs/test_multibase/test_multibase
```

You can insert a filter, e.g. `-head 1000` to do 1000 cases, or `pv -l` to see a progress bar.  The MC test has passed over 5 million cases with no failures.

2021-06-22 22:17 UTC, mvandeberg commented on programs/koinos-types/lang/koinos_codegen_cpp/rt/json.hpp
> +   util::encode_multibase( v.data(), v.size(), dest );
We need to make the default variable_blob encoding base64

2021-06-22 22:17 UTC, mvandeberg commented on programs/koinos-types/lang/koinos_codegen_cpp/rt/json.hpp
> +   util::encode_multibase( v.data(), v.size(), dest );
We need to make the default fixed_blob encoding base64

2021-06-22 22:21 UTC, mvandeberg commented on programs/koinos-types/lang/koinos_codegen_cpp/rt/multihash_json.hpp
> +   util::encode_multibase( serialized_bytes.c_str(), serialized_bytes.size(), encoded );
I know the default encoding is base58, but should we make that explicit here?

2021-06-22 22:23 UTC, mvandeberg commented on programs/koinos-types/lang/koinos_codegen_cpp/rt/util/multibase.hpp
> +/*
Is this commented code needed anymore? If not, can we clean it up?

2021-06-22 22:32 UTC, mvandeberg commented on tests/cpp/src/multibase_test.cpp
> +BOOST_AUTO_TEST_CASE( multibase_test )
These are all positive test cases. We need some specific negative test cases.

Some examples:

Illegal characters in an encoding.
Incorrect lengths (base64 with/without padding)

2021-06-25 19:43 UTC, mvandeberg approved these changes

2021-06-25 20:05 UTC, merged